In [ ]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
# import seaborn as sns
# from sodapy import Socrata
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", 100)
pd.set_option('display.float_format', '{:.4f}'.format)
path = "G:/Mi unidad/Maestría/TG/"
path = "C:/Users/PC/Desktop/tasas_mercado/Tasas/"

In [ ]:
## Falta PIB
## Calcular variaciones anuales de las variables

In [ ]:
# SocrataClient = Socrata("www.datos.gov.co", None)
# results = SocrataClient.get("w9zh-vetq", limit=80000,  where="fecha_corte >= '2020-01-01T00:00:00'") 
# tasascap = pd.DataFrame.from_records(results)
# tasascap

In [ ]:
tasascap = pd.read_csv(path+"src/tasas_colocacion.csv", decimal = ".", thousands = ",", encoding='utf-8')
#tasascap = pd.concat([tasascap, tasascap2], ignore_index=True).drop_duplicates()# tasascap2
tasascap.columns = [x.lower().replace(" ","_") for x in tasascap.columns]
tasascap["producto_de_crédito"].value_counts(normalize =True)

producto_de_crédito
Empresarial en pesos                                               0.1263
Tarjeta de crédito para ingresos superiores a 2 SMMLV              0.1002
Libranza otros                                                     0.0880
Libre inversión                                                    0.0781
Tarjeta de crédito para ingresos hasta 2 SMMLV                     0.0700
Tarjeta de crédito empresarial                                     0.0592
Factoring                                                          0.0441
Crédito rotativo                                                   0.0328
Corporativo                                                        0.0309
Vehículo                                                           0.0304
Sobregiro en cuenta corriente persona jurídica o persona natural   0.0262
Crédito popular productivo urbano (sin recursos de redescuento)    0.0250
Comerciales con recursos provenientes de redescuento               0.0246
Otros Comercial                                                    0.0216
Adquisición de vivienda no vis (colocación en pesos)               0.0191
Name: proportion, dtype: float64

In [ ]:
tasascap = pd.read_csv(path+"src/tasas_colocacion.csv", decimal = ".", thousands = ",", encoding='utf-8')
#tasascap = pd.concat([tasascap, tasascap2], ignore_index=True).drop_duplicates()# tasascap2
tasascap.columns = [x.lower().replace(" ","_") for x in tasascap.columns]
tasascap["fecha_corte"] = pd.to_datetime(tasascap["fecha_corte"], dayfirst=True, errors='coerce')
print(tasascap["fecha_corte"].min(), tasascap["fecha_corte"].max())

tasascap.rename(columns = {"avg_tasa_efectiva_promedio":"tasa", "montos_desembolsados":"monto",
                     "numero_de_creditos":"num_obl", "sum_montos_desembolsados":"monto", "sum_numero_de_creditos":"num_obl",
                     "producto_de_crédito":"producto", "plazo_de_crédito":"plazo", "nombre_entidad":"banco"}, inplace=True)

del tasascap["min_tasa_efectiva_promedio"], tasascap["max_tasa_efectiva_promedio"]
tasascap["tasa"] = tasascap["tasa"].astype(float)
tasascap["num_obl"] = tasascap["num_obl"].astype(int)
#["monto"] = tasascap["monto"].astype(float)/1000000000000
tasascap["fecha_corte"] = pd.to_datetime(tasascap["fecha_corte"])
tasascap["anomes"] = tasascap["fecha_corte"].dt.strftime("%Y-%m")
prods = [
'Adquisición de vivienda no vis (colocación en pesos)',
'Adquisición de vivienda vis (colocación en pesos)',
#'Consumo empleados',
#'Consumo otros',
'Crédito rotativo',
'Créditos de consumo de bajo monto',
'Libre inversión',
'Vehículo',
# 'Adquisición de vivienda no vis (colocación en uvr)',
# 'Adquisición de vivienda vis (colocación en uvr)',
'Adquisición leasing habitacional no vis (colocación en pesos)',
# 'Adquisición leasing habitacional no vis (colocación en uvr)',
# 'Comerciales con recursos provenientes de redescuento',
# 'Comerciales especiales directos por la banca de segundo piso',
# 'Comerciales especiales establecidos mediante leyes',
# 'Comerciales especiales otros',
# 'Construcción de proyectos de vivienda  vis (colocación en uvr)',
# 'Construcción de proyectos de vivienda no vis (colocación en pesos)',
# 'Construcción de proyectos de vivienda no vis (colocación en uvr)',
# 'Construcción de proyectos de vivienda vis (colocación en pesos)',
# 'Construcción de proyectos de vivienda vis (colocación en uvr)',
# 'Construcción de vivienda individual no vis (colocación en pesos)',
# 'Construcción de vivienda individual no vis (colocación en uvr)',
# 'Construcción de vivienda individual vis (colocación en pesos)',
# 'Construcción de vivienda individual vis (colocación en uvr)',
# 'Crédito popular productivo rural (con recursos de redescuento)',
# 'Crédito popular productivo rural (sin recursos de redescuento)',
# 'Crédito popular productivo urbano  (con recursos de redescuento)',
# 'Crédito popular productivo urbano (sin recursos de redescuento)',
# 'Crédito productivo de mayor monto (con recursos de redescuento)',
# 'Crédito productivo de mayor monto (sin recursos de redescuento)',
# 'Crédito productivo rural  (con recursos de redescuento)',
# 'Crédito productivo rural (sin recursos de redescuento)',
# 'Crédito productivo urbano  (con recursos de redescuento)',
# 'Crédito productivo urbano (sin recursos de redescuento)',
'Créditos educativos diferentes a libranza',
# 'Libranza adquisición de vivienda diferente de vis (colocación en pesos)',
'Libranza adquisición de vivienda vis (colocación en pesos)',
'Libranza educativo',
'Libranza otros',
# 'Microcrédito con recursos de redescuento entre 25 y 120 SMMLV',
# 'Microcrédito con recursos de redescuento menor a 25 SMMLV',
'Microcrédito entre 25 y 120 SMMLV',
'Microcrédito menor a 25 SMMLV',
# 'Otros Comercial',
# 'Empresarial - Tesoreria',
# 'Empresarial en UVR',
# 'Empresarial en pesos',
# 'Factoring',
# 'Financiero e institucional',
# 'Financiero e institucional para colocaciones con recursos de redescuento',
# 'Leasing financiero - financiación inmuebles diferente de habitacional',
# 'Leasing financiero - financiación maquinaria y equipo',
# 'Leasing financiero - financiación vehículos',
# 'Leasing financiero - otros',
'Adquisición leasing habitacional vis (colocación en pesos)',
# 'Adquisición leasing habitacional vis (colocación en uvr)',
# 'Corporativo',
# 'Construcción - financiación de proyectos viales',
# 'Construcción - financiación de proyectos viales en pesos',
# 'Libranza salud',
# 'Oficial o Gobierno',
# 'Otros Construcción',
# 'Otros Construcción (Colocacion en UVR)',
# 'Otros Construcción (Colocacion en pesos)',
# 'Sobregiro en cuenta corriente persona jurídica o persona natural',
# 'Sobregiro en cuenta corriente persona natural',
# 'Tarjeta de crédito empresarial',
'Tarjeta de crédito para ingresos hasta 2 SMMLV',
'Tarjeta de crédito para ingresos superiores a 2 SMMLV',
# 'Vivienda empleados'
]
tasascap = tasascap[tasascap["producto"].isin(prods)]
# tasascap = tasascap[tasascap["producto"].isin(["Crédito rotativo", "Libre inversión"])]

tasascap = tasascap[~tasascap["banco"].isin(["Fondo Nacional del Ahorro", "La Hipotecaria", "Bancoldex", "Confiar",
                                        "IRIS C.F.", "Bancamía S.A.", "Bancien", "Mibanco S.A.", "Banco Contactar",
                                        'Tuya','Crezcamos','Credifamilia','Financiera Juriscoop C.F.','Rappipay',
                                        'Banco GNB Sudameris','Banco Popular','Coopcentral','Banco Pichincha S.A.','Nu Colombia C.F.',
                                        "Caja de Vivienda Militar y de Polícia"])] # Excluidos por tasas atipicos
tasascap = tasascap[tasascap["tasa"] <= 50]
tasascap = tasascap[tasascap["num_obl"] >= 2]
# tasascap = tasascap[((tasascap["tasa"] >= 7) & (~tasascap["producto"].isin(['Vivienda', 'Consumo empleados']))) | (tasascap["producto"].isin(['Vivienda', 'Consumo empleados']))]
# tasascap = tasascap[(~tasascap["tipo_de_tasa"].isin(['-DTF', 'IB3', "DTFE", "IB6", "IB1"]))]
# tasascap = tasascap[(~tasascap["plazo"].isin(['A más de 7 años']))]
tasascap = tasascap[(tasascap["rango_monto_desembolsado"].notna())] # tienen nulos antes de 202309
tasascap ["banco"] = tasascap["banco"].str.replace("Compañía De Financiamiento","CF").str.replace("Cooperativa Financiera","CF")
tasascap["plazo"] = tasascap["plazo"].replace({'Más de 1 año y hasta 3 años':"(1-3]", 'Más de 3 años y hasta 5 años':"(3-5]",
                                                'Más de 5 años y hasta 7 años':"(5-7]",
                                                'Más de 7 años y hasta 10 años':"(7-10]", 'Más de 10 años':"(10-]",
                                                "Hasta 6 meses":"(0-1]", "Más de 6 meses y hasta 1 año":"(0-1]",
                                                'Hasta 30 días':"(0-1]", 'Entre 31 días y 1 año':"(0-1]"})
print(tasascap.shape)
print("Bancos:", tasascap["banco"].nunique())
tasascap.rename(columns = {"rango_monto_desembolsado":"rango_desembolso"}, inplace = True)

tasascap["prom_monto_porobl"] = tasascap["monto"]/tasascap["num_obl"]

# smlv = 1.82
# tasascap["ax"] = [x.split("SMLMV")[0] for x in tasascap["rango_desembolso"]]
# tasascap["ax"] = tasascap["ax"].str.extract(r'(\d+\.?\d*)').astype(float)*smlv
# tasascap["ax2"] = [x.split("SMLMV")[1] for x in tasascap["rango_desembolso"]]
# tasascap["ax2"] = tasascap["ax2"].str.extract(r'(\d+\.?\d*)').astype(float)*smlv
# tasascap["rang"] = [f"({x:.0f}-{y:.0f}]" for x, y  in zip(tasascap["ax"], tasascap["ax2"])]
# tasascap["rango_desembolso"] = np.where(tasascap["rango_desembolso"] == "Hasta 1 SMLMV", f"(0-{smlv:.0f}]", 
#                                 np.where(tasascap["rango_desembolso"] == "Mayor 300 SMLMV", f"({300*smlv:.0f}-]", tasascap["rang"]))
# del tasascap["ax"], tasascap["ax2"], tasascap["rang"]

print(tasascap["fecha_corte"].min(), tasascap["fecha_corte"].max())

tasascap

2022-07-01 00:00:00 2025-08-29 00:00:00
(190824, 11)
Bancos: 27
2023-09-29 00:00:00 2025-08-29 00:00:00

,banco,fecha_corte,tipo_de_persona,producto,plazo,tipo_de_tasa,rango_desembolso,tasa,monto,num_obl,anomes,prom_monto_porobl
3659,AV Villas,2023-09-29,Natural,Adquisición de vivienda no vis (colocación en pesos),Más de 15 años y hasta 20 años,FS,Hasta 135 SMLMV,16.9614,914285584.0000,8,2023-09,114285698.0000
3660,AV Villas,2023-09-29,Natural,Adquisición de vivienda no vis (colocación en pesos),Más de 15 años y hasta 20 años,FS,Mayor a 135 SMLMV y menor o igual a 235 SMLMV,17.2310,2532586220.0000,12,2023-09,211048851.6667
3662,AV Villas,2023-09-29,Natural,Adquisición de vivienda no vis (colocación en pesos),Más de 15 años y hasta 20 años,FS,Mayor a 335 SMLMV y menor o igual a 500 SMLMV,15.9500,934076708.0000,2,2023-09,467038354.0000
3664,AV Villas,2023-09-29,Natural,Adquisición de vivienda no vis (colocación en pesos),Más de 7 años y hasta 15 años,FS,Hasta 135 SMLMV,16.6750,683219182.0000,6,2023-09,113869863.6667
3665,AV Villas,2023-09-29,Natural,Adquisición de vivienda no vis (colocación en pesos),Más de 7 años y hasta 15 años,FS,Mayor a 135 SMLMV y menor o igual a 235 SMLMV,16.6750,1809440846.0000,9,2023-09,201048982.8889
...,...,...,...,...,...,...,...,...,...,...,...,...
747049,Scotiabank Colpatria S.A.,2025-08-29,Natural,Tarjeta de crédito para ingresos superiores a 2 SMMLV,Consumos entre 2 y 6 meses,FS,Mayor a 5 SMLMV menor o igual a 10 SMLMV,24.8004,1313242884.0000,3065,2025-08,428464.2362
747050,Scotiabank Colpatria S.A.,2025-08-29,Natural,Tarjeta de crédito para ingresos superiores a 2 SMMLV,Consumos entre 7 y 12 meses,FS,Mayor a 10 SMLMV menor o igual a 20 SMLMV,23.8093,1184466464.0000,1567,2025-08,755881.5980
747051,Scotiabank Colpatria S.A.,2025-08-29,Natural,Tarjeta de crédito para ingresos superiores a 2 SMMLV,Consumos entre 7 y 12 meses,FS,Mayor a 20 SMLMV,24.3770,10173426036.0000,16602,2025-08,612783.1608
747052,Scotiabank Colpatria S.A.,2025-08-29,Natural,Tarjeta de crédito para ingresos superiores a 2 SMMLV,Consumos entre 7 y 12 meses,FS,Mayor a 3 SMLMV menor o igual a 5 SMLMV,24.6246,384885678.0000,422,2025-08,912051.3697
747053,Scotiabank Colpatria S.A.,2025-08-29,Natural,Tarjeta de crédito para ingresos superiores a 2 SMMLV,Consumos entre 7 y 12 meses,FS,Mayor a 5 SMLMV menor o igual a 10 SMLMV,24.3714,902724013.0000,1142,2025-08,790476.3687

In [54]:
print(tasascap["producto"].value_counts(normalize =True))
print(tasascap["producto"].value_counts(normalize =False))

producto
Tarjeta de crédito para ingresos superiores a 2 SMMLV           0.2345
Libre inversión                                                 0.1917
Libranza otros                                                  0.1752
Tarjeta de crédito para ingresos hasta 2 SMMLV                  0.1464
Crédito rotativo                                                0.0981
Vehículo                                                        0.0733
Adquisición de vivienda no vis (colocación en pesos)            0.0416
Adquisición de vivienda vis (colocación en pesos)               0.0184
Adquisición leasing habitacional no vis (colocación en pesos)   0.0105
Créditos de consumo de bajo monto                               0.0050
Créditos educativos diferentes a libranza                       0.0044
Adquisición leasing habitacional vis (colocación en pesos)      0.0010
Libranza adquisición de vivienda vis (colocación en pesos)      0.0000
Name: proportion, dtype: float64
producto
Tarjeta de crédito para ingresos superiores a 2 SMMLV            44749
Libre inversión                                                  36576
Libranza otros                                                   33426
Tarjeta de crédito para ingresos hasta 2 SMMLV                   27943
Crédito rotativo                                                 18713
Vehículo                                                         13995
Adquisición de vivienda no vis (colocación en pesos)              7947
Adquisición de vivienda vis (colocación en pesos)                 3503
Adquisición leasing habitacional no vis (colocación en pesos)     1999
Créditos de consumo de bajo monto                                  951
Créditos educativos diferentes a libranza                          832
Adquisición leasing habitacional vis (colocación en pesos)         182
Libranza adquisición de vivienda vis (colocación en pesos)           8
Name: count, dtype: int64

In [18]:
tasascap["banco"].value_counts(normalize =True)

banco
Bancolombia                             0.0930
Scotiabank Colpatria S.A.               0.0816
Banco Davivienda                        0.0706
BBVA Colombia                           0.0700
Banco de Bogotá                         0.0698
Bancoomeva                              0.0668
Banco de Occidente                      0.0660
AV Villas                               0.0656
Banco Caja Social S.A.                  0.0590
Itaú                                    0.0540
Banco Serfinanza S.A.                   0.0519
Finandina                               0.0449
Banco Falabella S.A.                    0.0399
Banagrario                              0.0360
Banco Unión                             0.0275
Cotrafa                                 0.0208
Coltefinanciera                         0.0150
JFK CF                                  0.0144
CF de Antioquia                         0.0115
Lulo Bank                               0.0091
Banco W S.A.                            0.0087
Banco Santander                         0.0071
RCI Colombia S.A.                       0.0063
GM Financial Colombia S.A. CF           0.0051
Banco Mundo Mujer S.A.                  0.0043
Coofinep                                0.0007
Caja de Vivienda Militar y de Polícia   0.0003
Santander Consumer Colombia             0.0000
Name: proportion, dtype: float64

In [15]:
tasascap["tipo_de_tasa"].value_counts(normalize =True)

tipo_de_tasa
FS    0.9481
DTF   0.0363
IBR   0.0103
OTR   0.0031
IB1   0.0022
Name: proportion, dtype: float64

In [16]:
tasascap["tipo_de_persona"].value_counts(normalize =True)

tipo_de_persona
Natural   1.0000
Name: proportion, dtype: float64

In [41]:
tasascap["plazo"].value_counts(dropna = False, normalize=True)

plazo
(3-5]                            0.1569
(5-7]                            0.1323
(1-3]                            0.1238
Consumos entre 25 y 36 meses     0.0616
Avances en efectivo              0.0615
(0-1]                            0.0564
(7-10]                           0.0507
Consumos entre 19 y 24 meses     0.0499
Consumos entre 2 y 6 meses       0.0493
Consumos entre 7 y 12 meses      0.0486
Consumos a más de 36 meses       0.0460
Consumos entre 13 y 18 meses     0.0396
Más de 15 años y hasta 20 años   0.0307
(10-]                            0.0291
Consumos a un mes                0.0246
Más de 7 años y hasta 15 años    0.0232
A más de 20 años                 0.0066
Vivienda hasta 5 años            0.0061
Más de 2 años y hasta 3 años     0.0019
Más de 1 año y hasta 2 años      0.0010
Más de 3 años y hasta 4 años     0.0003
Más de 4 años y hasta 6 años     0.0001
Name: proportion, dtype: float64

In [22]:
tasascap["num_obl"].value_counts(dropna = False).head(15)

num_obl
2     18901
3     12350
4      9251
5      7270
6      5760
7      5332
8      4598
9      4046
10     3686
11     3358
12     2993
13     2764
14     2582
15     2356
16     2091
Name: count, dtype: int64

In [20]:
tasascap.isnull().sum()

banco               0
fecha_corte         0
tipo_de_persona     0
producto            0
plazo               0
tipo_de_tasa        0
rango_desembolso    0
tasa                0
monto               0
num_obl             0
anomes              0
dtype: int64

In [23]:
sorted(tasascap["producto"].fillna("0").unique())

['Adquisición de vivienda no vis (colocación en pesos)',
 'Adquisición de vivienda vis (colocación en pesos)',
 'Adquisición leasing habitacional no vis (colocación en pesos)',
 'Adquisición leasing habitacional vis (colocación en pesos)',
 'Crédito rotativo',
 'Créditos de consumo de bajo monto',
 'Créditos educativos diferentes a libranza',
 'Libranza adquisición de vivienda vis (colocación en pesos)',
 'Libranza otros',
 'Libre inversión',
 'Tarjeta de crédito para ingresos hasta 2 SMMLV',
 'Tarjeta de crédito para ingresos superiores a 2 SMMLV',
 'Vehículo']

In [25]:
tasascap["fecha_corte"].describe()

count                        190887
mean     2024-09-14 02:41:20.717911
min             2023-09-29 00:00:00
25%             2024-03-22 00:00:00
50%             2024-09-13 00:00:00
75%             2025-03-14 00:00:00
max             2025-08-29 00:00:00
Name: fecha_corte, dtype: object

In [24]:
tasascap["tasa"].describe()

count   190887.0000
mean        24.1839
std          6.5235
min          6.1700
25%         19.3946
50%         24.4500
75%         28.1436
max         49.9167
Name: tasa, dtype: float64

In [38]:
tasascap["tasa"].value_counts(normalize =True).head(20)*100

tasa
44.2500   0.2840
31.8900   0.1578
29.1100   0.1578
31.8400   0.1262
43.9100   0.1262
42.0400   0.0631
39.7900   0.0631
38.2725   0.0631
37.5520   0.0631
46.5367   0.0631
15.6900   0.0631
14.3900   0.0631
34.4900   0.0631
23.7300   0.0631
32.6754   0.0316
28.0445   0.0316
31.8479   0.0316
31.1526   0.0316
31.0651   0.0316
31.8438   0.0316
Name: proportion, dtype: float64

In [39]:
print(np.percentile(tasascap["tasa"], 2.25))
print(np.percentile(tasascap["tasa"], 5))
print(np.percentile(tasascap["tasa"], 95))
print(np.percentile(tasascap["tasa"], 97.5))

11.630030000000001
12.071985659564215
37.52633129983609
41.07084434797934

In [27]:
print(tasascap[tasascap["tasa"] <= 10].shape)
print(tasascap[tasascap["tasa"] >= 40].shape)

(429, 11)
(904, 11)

In [43]:
tasascap["rango_desembolso"].value_counts(dropna = False)

rango_desembolso
Mayor a 1 SMLMV menor o igual a 3 SMLMV          29588
Hasta 1 SMLMV                                    26562
Mayor a 6 SMLMV menor o igual a 12 SMLMV         16676
Mayor a 12 SMLMV menor o igual a 25 SMLMV        16216
Mayor a 3 SMLMV menor o igual a 6 SMLMV          15944
Mayor a 25 SMLMV menor o igual a 50 SMLMV        13717
Mayor a 3 SMLMV menor o igual a 5 SMLMV          12553
Mayor a 5 SMLMV menor o igual a 10 SMLMV         11518
Mayor a 50 SMLMV menor o igual a 100 SMLMV        9834
Mayor a 10 SMLMV menor o igual a 20 SMLMV         8848
Hasta 135 SMLMV                                   7162
Mayor a 20 SMLMV                                  6086
Mayor a 100 SMLMV menor o igual a 150 SMLMV       5327
Mayor a 150 SMLMV menor o igual a 300 SMLMV       3109
Mayor a 135 SMLMV y menor o igual a 235 SMLMV     2817
Mayor a 235 SMLMV y menor o igual a 335 SMLMV     1799
Mayor a 335 SMLMV y menor o igual a 500 SMLMV     1225
Mayor a 500 SMLMV                                  636
Mayor 300 SMLMV                                    559
Mayor a 1 SMLMV menor o igual a 2 SMLMV            245
Mayor a 2 SMLMV menor o igual a 3 SMLMV            197
Mayor a 3 SMLMV menor o igual a 4 SMLMV            182
Mayor a 4 SMLMV menor o igual a 5 SMLMV             24
Name: count, dtype: int64

In [51]:
# ax = tasascap[tasascap["fecha_corte"] >= "2025-01-01"]
ax = tasascap
ax = ax.groupby("producto").agg({"monto":"sum", "num_obl":"sum", "tasa":["mean", "median", "min", "max", "std"]}).reset_index()#.sort_values("num_obl", ascending=False)#.head(30)
ax.columns = ["producto", "monto", "num_obl", "tasa_mean", "tasa_median", "tasa_min", "tasa_max", "tasa_std"]
ax["tasa_cv"] = ax["tasa_std"]/ax["tasa_mean"].mean()*100
ax["%monto"] = ax["monto"]/ax["monto"].sum()*100
ax["%num_obl"] = ax["num_obl"]/ax["num_obl"].sum()*100
ax["prom_monto"] = ax["monto"]/ax["num_obl"]
ax = ax.sort_values("num_obl", ascending=False)#.head(30)
ax

,producto,monto,num_obl,tasa_mean,tasa_median,tasa_min,tasa_max,tasa_std,tasa_cv,%monto,%num_obl,prom_monto
11,Tarjeta de crédito para ingresos superiores a 2 SMMLV,69137238669541.5781,204716782,27.3091,26.1100,11.2200,42.0300,5.3450,25.2592,27.5452,74.4626,337721.4022
10,Tarjeta de crédito para ingresos hasta 2 SMMLV,14989903995591.0605,56966687,28.7777,27.8700,7.8000,42.0500,4.8968,23.1409,5.9722,20.7208,263134.5578
4,Crédito rotativo,11458639749649.9102,6496998,27.0674,26.1505,10.8200,42.0500,4.7670,22.5277,4.5653,2.3632,1763682.2036
9,Libre inversión,61402358904889.8281,4767758,24.6525,24.2566,8.1200,42.0500,5.0430,23.8319,24.4635,1.7342,12878665.1724
8,Libranza otros,38685933447207.4531,1144291,19.1946,18.3632,6.4500,39.6167,3.8273,18.0871,15.4130,0.4162,33807775.6857
5,Créditos de consumo de bajo monto,510258175268.0000,291073,38.2381,39.0067,21.4200,49.9167,7.3953,34.9484,0.2033,0.1059,1753024.7576
12,Vehículo,16975529856086.0195,251760,21.1086,20.3278,6.1700,41.8950,4.9119,23.2125,6.7633,0.0916,67427430.3149
1,Adquisición de vivienda vis (colocación en pesos),13454096783746.4297,165186,13.5100,13.2825,9.0000,20.9750,2.1134,9.9873,5.3603,0.0601,81448166.2111
0,Adquisición de vivienda no vis (colocación en pesos),20110674356740.1211,107354,14.0011,13.3300,9.5000,21.1600,2.5421,12.0133,8.0124,0.0390,187330461.4336
2,Adquisición leasing habitacional no vis (colocación en pesos),4042090815076.3501,13413,13.2945,12.3537,8.0000,21.1500,2.5244,11.9297,1.6104,0.0049,301356207.7892
6,Créditos educativos diferentes a libranza,22151132508.8700,2729,24.6734,23.7767,13.3500,41.7450,4.4697,21.1228,0.0088,0.0010,8116941.1905
3,Adquisición leasing habitacional vis (colocación en pesos),205216916698.0000,1678,12.0365,11.0000,10.0850,18.8900,1.4937,7.0588,0.0818,0.0006,122298520.0822
7,Libranza adquisición de vivienda vis (colocación en pesos),1655954006.0000,17,11.2246,10.9500,7.5000,14.0000,2.1075,9.9597,0.0007,0.0000,97409059.1765

In [53]:
# ax = tasascap[tasascap["fecha_corte"] >= "2025-01-01"]
ax = tasascap
ax = ax.groupby("banco").agg({"monto":"sum", "num_obl":"sum", "tasa":["mean", "median", "min", "max", "std"]}).reset_index()#.sort_values("num_obl", ascending=False)#.head(30)
ax.columns = ["banco", "monto", "num_obl", "tasa_mean", "tasa_median", "tasa_min", "tasa_max", "tasa_std"]
ax["tasa_cv"] = ax["tasa_std"]/ax["tasa_mean"].mean()*100
ax["%monto"] = ax["monto"]/ax["monto"].sum()*100
ax["%num_obl"] = ax["num_obl"]/ax["num_obl"].sum()*100
ax["prom_monto"] = ax["monto"]/ax["num_obl"]
ax = ax.sort_values("num_obl", ascending=False)#.head(30)
ax

,banco,monto,num_obl,tasa_mean,tasa_median,tasa_min,tasa_max,tasa_std,tasa_cv,%monto,%num_obl,prom_monto
26,Scotiabank Colpatria S.A.,31464503412748.8984,114648567,26.7585,26.2287,8.0000,42.0400,6.0838,24.7884,12.5359,41.7017,274443.0588
13,Bancolombia,53529101599178.3438,37759860,25.0745,25.1500,6.1700,49.9150,7.0819,28.8549,21.3267,13.7346,1417619.1755
12,Banco de Occidente,17211420410884.6895,25380345,21.1768,19.8271,6.5100,41.9000,6.1249,24.9557,6.8573,9.2317,678139.7341
5,Banco Falabella S.A.,13146853848260.9492,22776032,28.6493,27.4895,11.2200,42.0300,4.9930,20.3439,5.2379,8.2844,577223.1901
11,Banco de Bogotá,29093751704278.0000,14247057,21.9999,21.0723,9.8133,42.0200,6.2601,25.5064,11.5913,5.1821,2042088.5313
8,Banco Serfinanza S.A.,3965655393493.1099,14153580,25.6452,24.9177,12.5500,41.7500,5.5577,22.6447,1.5800,5.1481,280187.4433
1,BBVA Colombia,27212124731723.8008,11857290,22.0401,19.5220,7.8000,42.0500,7.0582,28.7584,10.8417,4.3129,2294969.9916
3,Banco Caja Social S.A.,9300556064749.0000,10204698,23.3679,23.2583,10.0000,41.0433,6.4340,26.2152,3.7055,3.7118,911399.4422
4,Banco Davivienda,30003639932758.3789,7569248,22.8038,22.4072,7.5000,49.9167,7.3954,30.1321,11.9538,2.7532,3963886.4961
0,AV Villas,11841161198008.3105,5457348,22.0360,22.0344,9.3100,41.7200,6.6015,26.8975,4.7177,1.9850,2169764.7279
19,Finandina,3947457860200.9502,3478628,25.8809,25.2725,10.5750,41.9500,5.0901,20.7394,1.5727,1.2653,1134774.3594
14,Bancoomeva,2478109847359.8398,2580362,25.7822,24.7728,12.4150,41.5340,5.1553,21.0049,0.9873,0.9386,960372.9428
21,Itaú,4883507900968.3301,2234522,26.7442,26.2736,10.8200,42.0300,6.4697,26.3604,1.9457,0.8128,2185482.1304
2,Banagrario,2284709717541.0000,1343669,20.3267,20.8333,6.4500,39.4500,5.2931,21.5663,0.9103,0.4887,1700351.5877
9,Banco Unión,887474768185.7800,263533,27.7888,26.0800,15.5200,41.7500,5.7172,23.2945,0.3536,0.0959,3367603.9365
16,Coltefinanciera,759945635864.7000,231639,26.7288,25.4900,16.6200,41.9100,3.7269,15.1850,0.3028,0.0843,3280732.6740
6,Banco Mundo Mujer S.A.,635193564043.0000,159124,29.9477,28.8046,24.6415,42.0500,4.7067,19.1771,0.2531,0.0579,3991814.9622
23,Lulo Bank,855514937336.2400,158131,24.6802,24.7300,18.2650,37.3600,3.0623,12.4771,0.3408,0.0575,5410165.8583
18,Cotrafa,674143451682.0000,130467,21.9015,20.7550,11.9267,38.4800,4.8786,19.8778,0.2686,0.0475,5167156.8418
10,Banco W S.A.,133998973226.3000,99837,24.7642,24.5600,14.0300,37.2800,4.0366,16.4470,0.0534,0.0363,1342177.4816
22,JFK CF,1534885268784.0000,88438,21.8856,21.3567,13.6200,39.0086,5.1414,20.9486,0.6115,0.0322,17355495.0223
7,Banco Santander,2553375281897.0000,34581,20.4035,20.1497,8.2600,31.4500,3.4725,14.1486,1.0173,0.0126,73837520.0803
24,RCI Colombia S.A.,1414498141862.0000,27188,23.5496,22.9125,16.5833,36.3783,3.3547,13.6684,0.5636,0.0099,52026561.0513
15,CF de Antioquia,123017546888.0000,24819,24.7653,24.3079,12.1300,40.1700,4.8205,19.6409,0.0490,0.0090,4956587.5695
20,GM Financial Colombia S.A. CF,1055657533188.0000,15534,22.7814,22.8125,15.1100,30.6467,2.1619,8.8085,0.4206,0.0057,67957868.7516
17,Coofinep,4734817806.0000,1213,28.6242,27.1600,15.9100,39.2900,7.0162,28.5871,0.0019,0.0004,3903394.7288
25,Santander Consumer Colombia,755214093.0000,16,26.5583,25.7850,25.4150,28.5133,1.3808,5.6259,0.0003,0.0000,47200880.8125

In [52]:
tasascap["anomes"].value_counts(dropna = False, normalize =True)
ax = tasascap
ax = ax.groupby(["anomes"]).agg({"monto":"sum", "num_obl":"sum", "tasa":["mean", "median", "min", "max", "std"]}).reset_index()#.sort_values("num_obl", ascending=False)#.head(30)
ax.columns = ["mes", "monto", "num_obl", "tasa_mean", "tasa_median", "tasa_min", "tasa_max", "tasa_std"]
ax["tasa_cv"] = ax["tasa_std"]/ax["tasa_mean"].mean()*100
ax["%monto"] = ax["monto"]/ax["monto"].sum()*100
ax["%num_obl"] = ax["num_obl"]/ax["num_obl"].sum()*100
ax["prom_monto"] = ax["monto"]/ax["num_obl"]
#ax.sort_values("monto", ascending=False).head(40)
ax

,mes,monto,num_obl,tasa_mean,tasa_median,tasa_min,tasa_max,tasa_std,tasa_cv,%monto,%num_obl,prom_monto
0,2023-09,2798432938491.0298,2032023,29.6973,29.8363,9.6667,42.0500,9.0394,37.0580,1.1149,0.7391,1377165.9762
1,2023-10,8383808356183.6602,8513744,29.8962,30.8205,7.5000,43.9100,8.2697,33.9024,3.3402,3.0967,984738.1312
2,2023-11,8541531215056.6396,8251029,29.4979,30.8994,7.7100,49.6931,7.8517,32.1889,3.4031,3.0012,1035207.9983
3,2023-12,11099144529000.1699,9900554,29.0603,30.3513,9.9300,49.4011,7.5512,30.9568,4.4220,3.6012,1121062.9758
4,2024-01,6675557580351.2803,7778091,28.2071,29.8666,7.2350,49.2900,6.6050,27.0777,2.6596,2.8292,858251.4116
5,2024-02,8654624106645.2803,11005355,27.5583,28.6201,8.3000,48.5922,6.6594,27.3007,3.4481,4.0030,786401.1753
6,2024-03,10668479808702.6992,13657167,26.6713,28.1290,6.1700,48.9725,6.2877,25.7772,4.2505,4.9676,781163.4586
7,2024-04,8464087214811.4297,8744906,26.1874,27.5879,7.8767,48.5795,6.3080,25.8603,3.3722,3.1808,967887.7297
8,2024-05,11887124168114.0801,14576615,25.3372,27.0846,6.5100,35.3550,5.8471,23.9706,4.7360,5.3020,815492.7717
9,2024-06,8814304171943.0508,11264481,25.0825,27.1167,7.6833,48.6053,5.7094,23.4062,3.5117,4.0973,782486.4876
10,2024-07,8648696993270.8096,11304084,24.3464,26.2739,8.7300,47.3290,5.2816,21.6524,3.4458,4.1117,765094.8979
11,2024-08,12264564637452.6797,13513490,23.8199,25.5767,7.2733,48.3900,5.4017,22.1448,4.8864,4.9153,907579.3624
12,2024-09,9888264091542.9805,11779137,23.4630,25.1950,7.9550,48.3650,5.4176,22.2100,3.9396,4.2845,839472.7128
13,2024-10,10409208642388.0996,12365665,22.8648,24.5657,7.7400,43.4967,5.1945,21.2954,4.1472,4.4978,841783.1667
14,2024-11,13970508344059.7305,15485207,22.5974,24.4909,7.4200,39.9700,5.2863,21.6719,5.5660,5.6325,902184.1519
15,2024-12,11069584559780.0605,12186129,21.7016,23.4658,7.0300,49.9167,4.8564,19.9092,4.4103,4.4325,908375.7902
16,2025-01,12081580354330.6191,12801035,21.2261,22.8500,6.8050,48.9060,4.2834,17.5602,4.8135,4.6562,943797.1503
17,2025-02,11552136466218.8496,10669005,21.5855,23.0740,8.1200,49.7633,4.6961,19.2521,4.6025,3.8807,1082775.4290
18,2025-03,10545791395040.3398,11955075,21.0638,22.4021,6.8400,49.8375,4.2084,17.2525,4.2016,4.3485,882118.3803
19,2025-04,11005840733709.4492,12102079,21.2779,22.5252,6.8600,49.6700,4.3677,17.9057,4.3849,4.4019,909417.3599
20,2025-05,15409822917343.9004,15534155,21.2518,22.2800,6.9000,49.9150,4.8190,19.7561,6.1395,5.6503,991996.2120
21,2025-06,11314234095397.4395,12072830,21.1631,22.2667,6.7200,49.4494,4.8858,20.0297,4.5077,4.3913,937165.0305
22,2025-07,11285874514217.5996,12040186,20.9394,22.0750,6.6700,49.7461,4.6048,18.8780,4.4964,4.3794,937350.5122
23,2025-08,15562546922957.7402,15393684,20.9271,21.9458,6.4500,49.3741,4.7510,19.4772,6.2003,5.5992,1010969.6238

In [34]:
ax = tasascap
ax = ax.groupby(["anomes", "plazo", "rango_desembolso"]).agg({"monto":"sum", "num_obl":"sum", "tasa":"mean"}).reset_index()#.sort_values("num_obl", ascending=False)#.head(30)
ax["monto"] = ax["monto"]/1000000
ax["prom_monto_porobl"] = ax["monto"]/ax["num_obl"] # millones

#ax.sort_values("monto", ascending=False).head(40)
tasascap = ax
tasascap

,anomes,plazo,rango_desembolso,monto,num_obl,tasa,prom_monto_porobl
0,2023-09,(0-1],(0-2],2354.7467,5557,32.6754,0.4237
1,2023-09,(0-1],(11-22],3040.5446,1165,28.0445,2.6099
2,2023-09,(0-1],(2-4],387.4963,253,31.8479,1.5316
3,2023-09,(0-1],(2-5],4218.0271,2617,31.1526,1.6118
4,2023-09,(0-1],(22-46],1939.7271,845,31.0651,2.2955
...,...,...,...,...,...,...,...
3164,2025-08,Más de 7 años y hasta 15 años,(610-910],24188.2415,52,11.8606,465.1585
3165,2025-08,Más de 7 años y hasta 15 años,(910-nan],11498.7724,32,11.9161,359.3366
3166,2025-08,Vivienda hasta 5 años,(246-428],2163.3756,12,11.0933,180.2813
3167,2025-08,Vivienda hasta 5 años,(246-nan],26830.4027,614,12.7280,43.6977
3168,2025-08,Vivienda hasta 5 años,(428-610],803.2681,6,11.6050,133.8780

In [ ]:
ax["monto"].describe()

In [ ]:
ax["prom_monto_porobl"].describe()

In [ ]:
# Datos banrep
banrep1 = pd.read_excel(path+"src/banrep1.xlsx")
banrep1 = banrep1.iloc[1:]
banrep1.columns = [x.lower().replace("í","i").replace("ó","o").replace(" ", "_") for x in banrep1.columns]
banrep1 = banrep1.replace({'-':np.nan})
banrep1["fecha"] = pd.to_datetime(banrep1["fecha"], format="%d/%m/%Y", errors='coerce')
#banrep1 = banrep1[banrep1["fecha"] >= "2020-01-01"]
banrep1["anomes"] = banrep1["fecha"].dt.strftime("%Y-%m")
print(banrep1["fecha"].min(), banrep1["fecha"].max())

print(banrep1.shape)

In [ ]:
banrep1

In [ ]:
bpmensual = banrep1[["anomes", "indice_de_precios_al_consumidor(dato_fin_de_mes)", 
                    "indice_de_precios_al_consumidor(variacion_porcentual__mensual)", 
                    "indice_de_precios_al_consumidor(variacion_porcentual__anual)", 
                    "indice_de_precios_del_productor_(ipp)(dato_fin_de_mes)",
                    "indice_de_precios_del_productor_(ipp)(variacion_porcentual__mensual)",
                    "indice_de_precios_del_productor_(ipp)(variacion_porcentual__anual)",
                    #"unidad_de_poder_adquisitivo_constante_(upac)(dato_fin_de_mes)",
                    "unidad_de_valor_real_(uvr)(dato_fin_de_mes)", 
                    "inflacion_total(dato_fin_de_mes)", 
                    "inflacion_de_alimentos(dato_fin_de_mes)"
                    ]].dropna()
bpmensual.columns = ["anomes", "ipc", "ipc_var_mes", "ipc_var_anual",
                   "ipp", "ipp_var_mes", "ipp_var_anual", "uvr", "inflacion", "inflacion_alimentos"]
for i in bpmensual.columns:
    if i != "anomes":
        bpmensual[i] = bpmensual[i].str.replace(",",".").astype(float)
bpmensual

In [ ]:
banrep1[["fecha", "unidad_de_poder_adquisitivo_constante_(upac)(dato_fin_de_mes)"]].dropna()

In [ ]:
banrep1

In [ ]:
banrep1.filter(like="_mes")

In [ ]:
banrep1.isnull().sum()

In [ ]:
banrep2 = pd.read_excel(path+"src/banrep2.xlsx", )
banrep2 = banrep2.iloc[1:]
banrep2.columns = [x.lower().replace("í","i").replace("ó","o").replace(" ", "_") for x in banrep2.columns]
banrep2 = banrep2.replace({'-':np.nan})
banrep2["fecha"] = pd.to_datetime(banrep2["fecha"], format="%d/%m/%Y", errors='coerce')
print(banrep2["fecha"].min(), banrep2["fecha"].max())
# banrep2 = banrep2[banrep2["fecha"] >= "2020-01-01"]
banrep2["anomes"] = banrep2["fecha"].dt.strftime("%Y-%m")
print(banrep2.shape)

In [ ]:
banrep2

In [ ]:
bpmensual2 = banrep2[["anomes",
                      "tasa_de_politica_monetaria(dato_fin_de_mes)",
                      "cartera_comercial_en_moneda_legal,_mensual(dato_fin_de_mes)",
                      "cartera_hipotecaria_en_moneda_legal,_mensual(dato_fin_de_mes)",
                      #"precio_oro_regalias,_mensual(dato_mes)"
                      "tasa_de_interés_de_colocacion_total,_mensual(promedio_mensual)"
                    ]].dropna()
bpmensual2.columns = ["anomes", "tasa_pmonetaria", "total_cartcom", "total_hipotec", "tasa_colocacion"]
for i in bpmensual2.columns:
    if i != "anomes":
        bpmensual2[i] = bpmensual2[i].str.replace(",",".").astype(float)
bpmensual2

In [ ]:
banrep2.filter(like="_diario)")

In [ ]:
banrep2

In [ ]:
bpdiario2 = banrep2[["fecha",
                      "tasa_interbancaria_(tib)(dato_diario)",
                      "indicador_bancario_de_referencia_(ibr)_a_1_mes,_efectiva(dato_diario)",
                      "indicador_bancario_de_referencia_(ibr)_a_3_meses,_efectiva(dato_diario)",
                      "indicador_bancario_de_referencia_(ibr)_a_6_meses,_efectiva(dato_diario)",
                      #"indicador_bancario_de_referencia_(ibr)_a_12_meses,_efectiva(dato_diario)" # no tiene 2020
                    ]].dropna()
bpdiario2.columns = ["fecha", "tasa_interban","ibr_1m", "ibr_3m", "ibr_6m"]
for i in bpdiario2.columns:
    if i != "fecha":
        bpdiario2[i] = bpdiario2[i].str.replace(",",".").astype(float)
bpdiario2["anomes"] = bpdiario2["fecha"].dt.strftime("%Y-%m")
bpdiario2 = bpdiario2.groupby("anomes").agg({"tasa_interban":["min","max","mean"], "ibr_1m":"mean", 
                                             "ibr_3m":"mean", "ibr_6m":"mean"}).reset_index()
bpdiario2.columns = ["anomes", "tasa_interban_min", "tasa_interban_max", "tasa_interban_mean", "ibr_1m", "ibr_3m", "ibr_6m"]
bpdiario2

In [ ]:
print(bpmensual2.shape)
bpmensual2 = pd.merge(bpmensual2, bpdiario2, on="anomes", how ="left")
print(bpmensual2.shape)
bpmensual2

In [ ]:
banrep3 = pd.read_excel(path+"src/banrep3.xlsx", )
banrep3 = banrep3.iloc[1:]
banrep3.columns = [x.lower().replace("í","i").replace("ó","o").replace(" ", "_") for x in banrep3.columns]
banrep3 = banrep3.replace({'-':np.nan})
banrep3["fecha"] = pd.to_datetime(banrep3["fecha"], format="%d/%m/%Y", errors='coerce')
print(banrep3["fecha"].min(), banrep3["fecha"].max())
# banrep3 = banrep3[banrep3["fecha"] >= "2020-01-01"]
banrep3["anomes"] = banrep3["fecha"].dt.strftime("%Y-%m")
print(banrep3.shape)

In [ ]:
banrep3

In [ ]:
bpmensual3 = banrep3[["anomes", "euro_-_cop/eur_-_tasa_media(dato_fin_de_mes)", "libra_esterlina_-_cop/gbp_-_tasa_media(dato_fin_de_mes)",
                        "reservas_internacionales_brutas(dato_fin_de_mes)", "reservas_internacionales_netas(dato_fin_de_mes)", 
                        "tasa_de_desempleo_-_total_nacional(dato_fin_de_mes)", "saldo_de_la_deuda_externa_total(dato_fin_de_mes)", 
                        "saldo_de_la_deuda_externa_del_sector_público(dato_fin_de_mes)", "saldo_de_la_deuda_externa_del_sector_privado(dato_fin_de_mes)",
                        "indice_de_términos_de_intercambio,_según_ipp(dato_fin_de_mes)",  "indice_de_precios_de_exportaciones,_según_ipp(dato_fin_de_mes)",
                        "indice_de_precios_de_importaciones,_según_ipp(dato_fin_de_mes)"]].dropna()
bpmensual3.columns = ["anomes", "euro_cop", "libra_cop", "reservas_inter_brutas", "reservas_inter_netas",
                      "tasa_desempleo", "deuda_ext_total", "deuda_ext_publico",
                      "deuda_ext_privado", "ipinterc", "ipexport", "ipimport"]
for i in bpmensual3.columns:
    if i != "anomes":
        bpmensual3[i] = bpmensual3[i].str.replace(".","").str.replace(",",".").astype(float)
bpmensual3

In [ ]:
bpmensual32 = banrep3[["anomes",
                        "producto_interno_bruto_(pib)_nominal,_trimestral,_metodologia:_2015(dato_fin_de_trimestre)",
                        "producto_interno_bruto_(pib)_nominal,_trimestral,_metodologia:_2015(variacion_porcentual__anual)",
                        "producto_interno_bruto_(pib)_nominal,_trimestral,_metodologia:_2015(variacion_porcentual__año_corrido)",
                        ]].dropna()
bpmensual32.columns = ["anomes", "pib", "pib_var_anual", "pib_var_anualcorrido"]
for i in bpmensual32.columns:
    if i != "anomes":
        bpmensual32[i] = bpmensual32[i].str.replace(".","").str.replace(",",".").astype(float)
bpmensual32["ano"] = bpmensual32["anomes"].str[:4]
bpmensual32["anomes"] = pd.to_datetime(bpmensual32["anomes"], format="%Y-%m", errors='coerce')
bpmensual32["trimestre"] = bpmensual32["anomes"].dt.quarter
bpmensual32

In [ ]:
bpmensual3["ano"] = bpmensual3["anomes"].str[:4]
bpmensual3["anomes"] = pd.to_datetime(bpmensual3["anomes"], format="%Y-%m", errors='coerce')
bpmensual3["trimestre"] = bpmensual3["anomes"].dt.quarter
bpmensual3

In [ ]:
bpmensual3

In [ ]:
del bpmensual32["anomes"]
bpmensual3 = pd.merge(bpmensual3, bpmensual32, on=["ano","trimestre"], how="left")
del bpmensual3["ano"], bpmensual3["trimestre"]
bpmensual3["anomes"] = bpmensual3["anomes"].dt.strftime("%Y-%m")
bpmensual3

In [ ]:
fed = pd.read_csv(path+"src/fed.csv")
fed.rename(columns={"observation_date":"anomes", "FEDFUNDS":"tasa_fed"}, inplace=True)
fed["anomes"] = pd.to_datetime(fed["anomes"], format="%Y-%m-%d", errors='coerce')
print(fed["anomes"].min(), fed["anomes"].max())
fed["anomes"] = fed["anomes"].dt.strftime("%Y-%m")
fed

In [ ]:
import yfinance as yf

dicc = {
# Divisas
"EURUSD=X":"euro_dolar", 
"GBPUSD=X":"libra_dolar", 
"JPY=X":"yen_dolar",
"CNY=X":"yuan_dolar", 
"COP=X": "usd_cop",
"DX-Y.NYB": "dxy_dolar",
# Tasas de Bonos del Tesoro de EE.UU.
"^IRX":"bonos_usa_1y", 
"^FVX":"bonos_usa_5y", 
"^TNX":"bonos_usa_10y", 
"^TYX":"bonos_usa_30y",
# Índices bursátiles globales
"^GSPC": "sp500",
"^IXIC": "nasdaq",
"^DJI": "dow_jones",
"EEM": "msci_emergentes",
"URTH": "msci_world",
# Índices de volatilidad / riesgo
"^VIX": "vix",
# Petróleo
"CL=F": "petrol_wti",
"BZ=F": "petrol_brent",
# Metales
"GC=F": "oro",
"SI=F": "plata",
"HG=F": "cobre",
# Energía
"NG=F": "gas_natural",
# Tasas internacionales / futuros
"SR1=F": "sofr_futuro_1m",
"GE=F": "eurodolar_futuro",
# ETFs de bonos internacionales
"TLT": "bonos_largo_usa",
"SHY": "bonos_corto_usa",
"LQD": "bonos_corps_inversion",
"HYG": "bonos_high_yield",
"EMB": "bonos_mercados_emergentes",
# Criptomonedas (liquidez global)
"BTC-USD": "bitcoin",
"ETH-USD": "ethereum"
}
yahoo = pd.DataFrame(bpmensual["anomes"])

for sym, name in dicc.items():
    #print(name)
    _temp = yf.Ticker(sym)
    _temp = _temp.history(period="10y")
    _temp = _temp.reset_index()
    _temp.rename(columns = {"Date":"anomes", "Close":name}, inplace = True)
    _temp["anomes"] = pd.to_datetime(_temp["anomes"])
    _temp["anomes"] = _temp["anomes"].dt.strftime("%Y-%m")
    _temp = _temp.sort_values("anomes", ascending = False).drop_duplicates("anomes")[["anomes", name]]
    #_temp = _temp.groupby("anomes")[name].mean().reset_index()
    yahoo = pd.merge(yahoo, _temp, on="anomes", how="left")
print(yahoo["anomes"].min(), yahoo["anomes"].max())
yahoo

In [ ]:
usura = pd.read_excel(path+"src/usura.xls")
usura["anomes"] = pd.to_datetime(usura["anomes"], format="%Y-%m", errors='coerce')
usura["anomes"] = usura["anomes"].dt.strftime("%Y-%m")
usura["tasa_banc_corriente"] = usura["tasa_banc_corriente"].replace({" ":np.nan}).astype(float)*100
usura["tasa_banc_corriente"] = usura["tasa_banc_corriente"].fillna(method='bfill')
usura["tasa_usura"] = usura["tasa_usura"].replace({" ":np.nan}).astype(float)*100
usura["tasa_usura"] = usura["tasa_usura"].fillna(method='bfill')
usura = usura.groupby("anomes").agg({"tasa_banc_corriente":"mean", "tasa_usura":"mean"}).reset_index()

print(usura["anomes"].min(), usura["anomes"].max())

usura

In [ ]:
bpmensual2

In [ ]:
tasascap

In [ ]:
tasascap["anomes"] = tasascap["anomes"].astype(str)
bpmensual["anomes"] = bpmensual["anomes"].astype(str)
print(tasascap.shape)
df = pd.merge(tasascap, bpmensual, on="anomes", how ="left")
print(df.shape)

bpmensual["anomes"] = bpmensual["anomes"].astype(str)
df = pd.merge(df, bpmensual2, on="anomes", how ="left")
print(df.shape)

bpmensual3["anomes"] = bpmensual3["anomes"].astype(str)
df = pd.merge(df, bpmensual3, on="anomes", how ="left")
print(df.shape)

usura["anomes"] = usura["anomes"].astype(str)
df = pd.merge(df, usura, on="anomes", how ="left")
print(df.shape)

fed["anomes"] = fed["anomes"].astype(str)
df = pd.merge(df, fed, on="anomes", how ="left")
print(df.shape)

yahoo["anomes"] = yahoo["anomes"].astype(str)
df = pd.merge(df, yahoo, on="anomes", how ="left")
print(df.shape)
del df["sofr_futuro_1m"]

df["pib_percap"] = df["pib"]/53400 # Automatizar

cats = []
numerics = []
for i in df.columns:
    try:
        df[i].astype(float)
        numerics.append(i)
    except:
        cats.append(i)
df#.sample(5)
df["anomes"] = pd.to_datetime(df["anomes"])
df = df.sort_values("anomes").set_index("anomes")
df["tasa_banc_corriente_var_mes"] = df["tasa_banc_corriente"].pct_change() * 100
df["tasa_banc_corriente_var_anual"] = df["tasa_banc_corriente"].pct_change(12) * 100
df = df.reset_index()
df

In [ ]:
k

## EDA

In [ ]:
df[["tasa", "tasa_colocacion", "tasa_pmonetaria", "tasa_fed", "tasa_banc_corriente", "tasa_usura"]].corr()

In [ ]:
ax = df.isnull().sum().reset_index().sort_values(0, ascending = False)
ax["%"] = (ax[0]/df.shape[0]*100)
print(df.shape)
ax.head(15)

In [ ]:
df.filter(like="pib")

In [ ]:
df

In [ ]:
yname = "tasa"

In [ ]:
cors = df[numerics].corr()
cors = cors[[yname]][yname].sort_values(ascending = False)
display(cors.head(25))
display(cors.tail(25))

In [ ]:
# Eliminar por multicolinealidad
# cols = ["tasa_usura", "reservas_inter_netas", "tasa_interban_max", "tasa_interban_min", "uvr", "ibr_1m"]
# df.drop(columns=cols, inplace = True)
# numerics = list(set(numerics) - set(cols))

In [ ]:
ax = df[numerics].corr().reset_index()
ax = ax.melt(id_vars=["index"], value_vars=ax.columns[1:])
ax.columns = ["var1", "var2", "cor"]
ax = ax.drop_duplicates("cor")
ax = ax.sort_values(by="cor", ascending=False)
ax = ax[ax["var1"] != ax["var2"]]
display(ax.head(15)) 
display(ax.tail(15))

In [ ]:
df

In [ ]:
plt.figure(figsize=(8,5))
print(df[yname].describe())
plt.hist(df[yname], bins=30, edgecolor='black')
plt.title("Distribución de "+yname)
plt.xlabel(yname)
plt.ylabel("Frecuencia")
plt.tight_layout()
plt.show()

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

ax = tasascap
ax = ax.groupby(["anomes"]).agg({"monto":"sum", "num_obl":"sum", "tasa":["mean", "median", "min", "max", "std"]}).reset_index()#.sort_values("num_obl", ascending=False)#.head(30)
ax.columns = ["mes", "monto", "num_obl", "tasa_mean", "tasa_median", "tasa_min", "tasa_max", "tasa_std"]
ax["tasa_cv"] = ax["tasa_std"]/ax["tasa_mean"].mean()*100
ax["%monto"] = ax["monto"]/ax["monto"].sum()*100
ax["%num_obl"] = ax["num_obl"]/ax["num_obl"].sum()*100
ax["prom_monto"] = ax["monto"]/ax["num_obl"]
#ax.sort_values("monto", ascending=False).head(40)
ax

def plot_time_series(df, date_col="date", value_col="value", title="Serie temporal"):
    """
    Grafica una serie temporal con puntos y líneas que los unen.
    Parámetros:
      - df: DataFrame con las columnas de fecha y valor
      - date_col: nombre de la columna de fecha
      - value_col: nombre de la columna de valor
      - title: título del gráfico
    """
    df = df.copy()
    df[date_col] = pd.to_datetime(df[date_col])

    fig, axy = plt.subplots(figsize=(13, 5))

    # Línea + puntos
    axy.plot(df[date_col], df[value_col], marker='o', linewidth=1.5, markersize=6, label = "Media")
    axy.plot(df[date_col], ax["tasa_median"], marker='o', linewidth=1.5, markersize=6, label = "Mediana")

    # Formato de fechas en eje X
    axy.xaxis.set_major_locator(mdates.AutoDateLocator())
    axy.xaxis.set_major_formatter(mdates.ConciseDateFormatter(axy.xaxis.get_major_locator()))

    axy.set_title(title)
    axy.set_xlabel("Fecha")
    axy.set_ylabel(value_col)
    axy.grid(alpha=0.3)
    axy.legend()
    plt.tight_layout()
    plt.show()

# Llamada
plot_time_series(ax, "mes", "tasa_mean", title="Comportamiento de la tasa de desembolso")

In [ ]:
ax

In [ ]:
df

In [ ]:
def scatter_line(df, yname, xnames):
    for x in xnames:
        plt.figure(figsize=(9,5))

        # Scatter
        plt.scatter(df[x], df[yname], s=20)

        # Correlación
        corr = df[[yname, x]].corr().iloc[0, 1]
        plt.text(
            0.915, 0.04,
            f'r: {corr:.4f}',
            transform=plt.gca().transAxes,
            fontsize=9,
            bbox=dict(facecolor='white', alpha=0.5)
        )

        # Línea de regresión
        ax = df[[x, yname]].dropna()
        m, b = np.polyfit(ax[x], ax[yname], 1)  
        plt.plot(ax[x], m*ax[x] + b, linewidth=2, color = "black")

        # Etiquetas
        plt.xlabel(x.title().replace("_"," "))
        plt.ylabel(yname.title().replace("_"," "))
        plt.title(f"{yname.title().replace("_"," ")} vs {x.title().replace("_"," ")}")
        plt.grid(True, alpha=0.3)
        plt.legend()
        #plt.ylim([df[yname].min()*0.05, df[yname].max()*1.1])
        plt.tight_layout()
        plt.show()

xnames = cors.reset_index()["index"].tolist()[1:5] + cors.reset_index()["index"].tolist()[-5:]
scatter_line(df, yname, xnames)

In [ ]:
plt.hist(df["tasa"]., )

In [ ]:
scatter_line(df, "usd_cop", ["sp500"])

In [ ]:
df

In [ ]:
# df.drop(columns = ["tasa_usura", "reservas_inter_brutas", "tasa_interban_max", "tasa_pmonetaria", "uvr_nivel", "sofr_futuro_1m"], inplace =True)