In [7]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt
from joblib import Parallel, delayed
from datetime import datetime
import sys
from pathlib import Path

import sys
# sys.path.append("../src")
sys.path.append(str(Path.cwd().parent))

from indicators.indicators import load_symbol, build_indicators
from signals import build_signals

import vars

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 40)
pd.set_option('display.max_colwidth', 200)

color_back = "#0d1117"

path_repo = vars.path_repo
path_data = vars.path_data

In [2]:
symbs = vars.symbs

symbs_crypto = [x for x in symbs if "-USD" in x]
symbs_forex = [x for x in symbs if "=X" in x]
symbs_stocks = [x for x in symbs if x not in symbs_crypto + symbs_forex]

print("Total:", len(symbs))
print("Crypto :", len(symbs_crypto), f"({(len(symbs_crypto)/len(symbs))*100:.0f}%)")
print("Forex:", len(symbs_forex), f"({(len(symbs_forex)/len(symbs))*100:.0f}%)")
print("Stocks:", len(symbs_stocks), f"({(len(symbs_stocks)/len(symbs))*100:.0f}%)")

Total: 12
Crypto : 3 (25%)
Forex: 3 (25%)
Stocks: 6 (50%)

In [3]:
symb = "ETH-USD"
df = load_symbol(symb, "1h", 400) 
df = build_indicators(df)
df = build_signals(df)
df

Price,Close,High,Low,Open,Volume,date,EMA20,EMA50,EMA200,RSI,MACD,MACD_signal,MACD_hist,BB_upper,BB_mid,BB_lower,BB_position,STOCH_K,STOCH_D,ATR,OBV,OBV_EMA,ADX,ADX+DI,ADX-DI,prev26,prev52,VPVMA,VPVMAS,VWAP,spread,vol_ma,volume_ma,volume_increasing,order_flow,volatility,CMF,PSAR,WillR,Donchian_high,Donchian_low,ema50_distance,MACD_bearish_div,MACD_bullish_div,sign_macd_rsi_robust,sign_macd_rsi_simple,sign_macd_rsi_simple_break,sign_macd_rsi_simple_bb_pos,sign_macd_rsi_bb,sign_macd_rsi_bb_ema,ind_adx,sign_adx_crec,sign_adx_crec_rsi,sign_adx_rsi,sign_adx_rsi_robust,sign_adx_rsi_xtrem,sign_vpvma,sign_sinergia,sign_rsi_bb_rever,sign_ma_macd,str_squ_kel_bb,sign_gold,ind_3ema,sign_rsi30,sign_rsi20,sign_rsi15,trend_adx,sign_pullb_ema,sign_rsi_div,ind_vwap_deviation,sign_supo_resi,ind_volume_anomaly,ind_compress_range,sign_sobreextema,sign_stochastic,sign_cmf,sign_elderray,sign_willr,sign_donchian,sign_liquidsweep,sign_macd_div1,sign_macd_div3,sign_macd_div5,sign_random,sign_random2,sign_random3
Datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-09-12 08:00:00+00:00,4517.217285,4532.402344,4515.563965,4526.828613,741388288,2025-09-12 08:00:00+00:00,4481.997659,4429.685994,4360.229558,63.463830,35.056878,31.434895,3.621983,4568.483437,4471.463037,4374.442637,0.735797,70.749555,82.057307,26.477805,1.583831e+10,1.588849e+10,37.331910,33.147042,12.537875,4441.526855,4312.413574,216.254141,4090.372726,4513.243358,0.003728,392150220.8,392150220.8,True,sell,0.004171,-0.125933,4514.938092,-29.182080,4559.395508,4387.414062,0.019760,False,False,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,2.0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,1
2025-09-12 09:00:00+00:00,4514.791992,4526.752441,4507.834961,4517.355469,0,2025-09-12 09:00:00+00:00,4485.120929,4433.023484,4361.767493,62.657574,33.354339,31.818784,1.535556,4572.857275,4475.245361,4377.633448,0.702571,53.826476,69.530255,25.937781,1.583831e+10,1.588371e+10,37.402016,31.420221,14.013151,4444.264160,4304.999512,-1553.895784,3029.209204,4513.243358,0.004190,392150220.8,392150220.8,False,sell,0.004119,-0.125933,4559.395508,-31.156694,4559.395508,4397.961914,0.018445,False,False,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,2.0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,1,0,0
2025-09-12 10:00:00+00:00,4515.354980,4521.300293,4510.381348,4515.334473,0,2025-09-12 10:00:00+00:00,4488.000362,4436.252170,4363.295726,62.775794,31.685246,31.792076,-0.106830,4576.180112,4479.576782,4382.973453,0.685181,41.912707,55.496246,24.865007,1.583831e+10,1.587939e+10,37.467115,30.434683,13.573610,4432.722168,4313.854004,-4130.174259,1720.347011,4513.243358,0.002418,392150220.8,392150220.8,False,buy,0.004055,-0.125933,4558.364297,-30.817986,4559.395508,4403.165527,0.017831,False,False,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2.0,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,0,0,0,0,0
2025-09-12 11:00:00+00:00,4519.357422,4534.915527,4515.112793,4515.663574,0,2025-09-12 11:00:00+00:00,4490.986749,4439.511200,4364.848579,63.656689,30.335750,31.500811,-1.165061,4577.585126,4484.945557,4392.305987,0.685730,34.932968,43.557384,24.503416,1.583831e+10,1.587547e+10,37.912444,32.646717,12.790061,4416.827148,4327.397949,-4349.172910,583.432846,4513.243358,0.004382,392150220.8,392150220.8,False,buy,0.003898,-0.125933,4557.353710,-30.212970,4559.395508,4409.294922,0.017985,False,False,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2.0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0
2025-09-12 12:00:00+00:00,4528.465820,4529.554688,4507.103516,4520.372070,0,2025-09-12 12:00:00+00:00,4494.556184,4442.999616,4366.476611,65.648923,29.659341,31.132517,-1.473176,4579.525245,4490.416968,4401.308691,0.713498,39.406721,38.750799,24.356828,1.583831e+10,1.587193e+10,37.787746,30.497255,14.296755,4429.109863,4331.400879,-4075.502222,-175.307444,4513.243358,0.004958,392150220.8,392150220.8,False,buy,0.003901,-0.125933,4556.363335,-29.182446,4559.395508,4412.189941,0.019236,False,False,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2.0,0,0,0,0,0,0,0,0,-1,-1,0,0,0,0,0,0,-1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-10-05 19:00:00+00:00,2708.419922,2712.479980,2706.080078,2710.300049,21681152,2026-10-05 19:00:00+00:00,2709.814676,2705.886111,2692.955569,49.491465,-0.311354,1.541899,-1.853254,2735.017074,2714.106482,2693.195890,0.364027,57.219469,45.008003,12.718370,7.405207e+10,7.548798e+10,18.510711,21.780091,24.218931,2701.709961,2681.219971,174.484706,1611.810940,2709.112867,0.002363,380830668.8,380830668.8,False,sell,0.003369,0.168794,2722.313890,-46.029061,2737.370117,2679.129883,0.000936,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1.0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0
2026-10-05 20:00:00+00:00,2711.840088,2715.000000,2706.000000,2708.889893,0,2026-10-05 20:00:00+00:00,2710.007573,2706.119600,2693.143474,51.579013,-0.064659,1.220588,-1.285247,2732.996712,2713.256982,2693.517253,0.464111,61.615447,55.671003,12.452772,7.405207e+10,7.535123e+10,17.325997,22.101197,22.968663,2700.520020,2680.860107,-331.481751,1457.257514,2709.112867,0.003319,368063718.4,368063718.4,False,buy,0.003379,0.151325,2719.722850,-39.726933,2737.370117,2679.129883,0.002114,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0
2026-10-05 21:00:00+00:00,2711.260010,2712.620117,2710.909912,2712.209961,0,2026-10-05 21:00:00+00:00,2710.126852,2706.321185,2693.323738,51.192555,0.083084,0.993087,-0.910003,2731.661991,2712.605981,2693.549972,0.464684,62.317238,60.384051,11.685446,7.405207e+10,7.522750e+10,16.225905,21.870155,22.728552,2701.129883,2688.449951,-1383.696822,1210.101930,2709.112867,0.000631,353169920.0,353169920.0,False,sell,0.003364,0.182226,2717.287272,-40.795807,2737.370117,2679.129883,0.001825,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-1.0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,-1,1
2026-10-06 00:00:00+00:00,2718.270020,2718.270020,2709.870117,2709.870117,305199104,2026-10-06 00:00:00+00:00,2710.902392,2706.789767,2693.571960,55.528903,0.757093,0.945888,-0.188795,2729.327228,2711.991980,2694.656732,0.681077,68.838310,64.256998,11.450764,7.435726e+10,7.514462e+10,15.489829,24.248555,21.537630,2705.500000,2684.810059,-1322.189184,935.619096,2718.270020,0.003090,349131750.4,349131750.4,False,buy,0.003375,0.230586,2679.129883,-22.264030,2733.399902,2679.129883,0.004241,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1.0,1,0,0,0,0,0,0,0,1,-1,0,0,0,0,0,0,0,0,0
2026-10-06 01:00:00+00:00,2716.790039,2722.530029,2715.530029,2718.399902,172712960,2026-10-06 01:00:00+00:00,2711.463120,2707.181934,2693.802986,54.429407,1.158474,0.988405,0.170069,2729.461652,2712.059485,2694.657318,0.635919,76.107889,69.087812,11.132852,7.418455e+10,7.505318e+10,15.201636,25.892731,20.570329,2701.840088,2685.189941,-1646.832987,410.845936,2717.735168,0.002577,340568524.8,340568524.8,False,sell,0.003138,0.255817,2679.912686,-25.203410,2733.399902,2679.129883,0.003549,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [4]:
cols_sign = [col for col in df.columns if col.startswith("sign_")] 
cols_indic = [col for col in df.columns if not col.startswith("sign_")] 
order = sorted(cols_sign)
df = df[order]

print("Signals   :", len(cols_sign))
print("Indicators:", len(cols_indic))

Signals   : 35
Indicators: 51

In [8]:
res = []
for j in cols_sign:
    buys = df[df[j].isin([1])].shape[0]
    sells = df[df[j] == -1].shape[0] 
    n = buys + sells
    res.append(pd.DataFrame({"signal":[j], "n":[n], "%":[(n/len(df))*100], "buys":[buys], "buys%":[(buys/len(df))*100],
                              "sells":[sells],"sells%":[(sells/len(df))*100]}))
print(len(df))
res = pd.concat(res).sort_values("%", ascending = False)
res.head(40)

9293

,signal,n,%,buys,buys%,sells,sells%
0,sign_cmf,4128,44.420532,1827,19.659959,2301,24.760572
0,sign_ma_macd,3689,39.696546,1746,18.788335,1943,20.908210
0,sign_adx_crec,2370,25.503067,1067,11.481760,1303,14.021306
0,sign_random3,1835,19.746045,929,9.996772,906,9.749274
0,sign_pullb_ema,1658,17.841386,814,8.759281,844,9.082105
0,sign_vpvma,1438,15.474013,692,7.446465,746,8.027548
0,sign_sobreextema,1372,14.763801,769,8.275046,603,6.488755
0,sign_elderray,1295,13.935220,636,6.843861,659,7.091359
0,sign_willr,1240,13.343377,584,6.284300,656,7.059077
0,sign_rsi30,1078,11.600129,503,5.412676,575,6.187453
0,sign_macd_div5,962,10.351878,499,5.369633,463,4.982245
0,sign_random,938,10.093619,471,5.068331,467,5.025288
0,sign_donchian,836,8.996019,432,4.648660,404,4.347358
0,sign_liquidsweep,821,8.834607,400,4.304315,421,4.530292
0,sign_stochastic,683,7.349618,319,3.432691,364,3.916927
0,sign_macd_div3,579,6.230496,300,3.228236,279,3.002260
0,sign_sinergia,575,6.187453,339,3.647907,236,2.539546
0,sign_rsi_bb_rever,570,6.133649,284,3.056064,286,3.077585
0,sign_supo_resi,479,5.154417,255,2.744001,224,2.410416
0,sign_random2,474,5.100613,227,2.442699,247,2.657915
0,sign_macd_rsi_bb,446,4.799311,222,2.388895,224,2.410416
0,sign_macd_div1,193,2.076832,100,1.076079,93,1.000753
0,sign_gold,184,1.979985,92,0.989992,92,0.989992
0,sign_rsi20,174,1.872377,69,0.742494,105,1.129883
0,sign_rsi_div,153,1.646401,84,0.903906,69,0.742494
0,sign_macd_rsi_robust,114,1.226730,25,0.269020,89,0.957710
0,sign_macd_rsi_simple,82,0.882385,21,0.225977,61,0.656408
0,sign_rsi15,52,0.559561,18,0.193694,34,0.365867
0,sign_macd_rsi_simple_bb_pos,40,0.430432,12,0.129129,28,0.301302
0,sign_macd_rsi_bb_ema,35,0.376628,19,0.204455,16,0.172173
0,sign_adx_crec_rsi,5,0.053804,3,0.032282,2,0.021522
0,sign_macd_rsi_simple_break,2,0.021522,0,0.000000,2,0.021522
0,sign_adx_rsi,2,0.021522,2,0.021522,0,0.000000
0,sign_adx_rsi_robust,0,0.000000,0,0.000000,0,0.000000
0,sign_adx_rsi_xtrem,0,0.000000,0,0.000000,0,0.000000