In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt
from joblib import Parallel, delayed
from datetime import datetime
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from mdt import load_symbol

import vars

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_colwidth', 200)

color_back = "#0d1117"

path_repo = vars.path_repo
path_data = vars.path_data

In [2]:
symbs = vars.symbs

symbs_crypto = [x for x in symbs if "-USD" in x]
symbs_forex = [x for x in symbs if "=X" in x]
symbs_stocks = [x for x in symbs if x not in symbs_crypto + symbs_forex]

print("Total:", len(symbs))
print("Crypto :", len(symbs_crypto), f"({(len(symbs_crypto)/len(symbs))*100:.0f}%)")
print("Forex:", len(symbs_forex), f"({(len(symbs_forex)/len(symbs))*100:.0f}%)")
print("Stocks:", len(symbs_stocks), f"({(len(symbs_stocks)/len(symbs))*100:.0f}%)")

Total: 12
Crypto : 3 (25%)
Forex: 3 (25%)
Stocks: 6 (50%)

In [3]:
df = load_symbol("BTC-USD", "1h", 400) 
df

Price,Close,High,Low,Open,Volume,date,EMA20,EMA50,EMA200,RSI,MACD,MACD_signal,MACD_hist,BB_upper,BB_mid,BB_lower,BB_position,STOCH_K,STOCH_D,ATR,OBV,OBV_EMA,ADX,ADX+DI,ADX-DI,prev26,prev52,VPVMA,VPVMAS,VWAP,spread,vol_ma,volume_ma,volume_increasing,order_flow,volatility,CMF,PSAR,WillR,Donchian_high,Donchian_low,ema50_distance,MACD_bearish_div,MACD_bullish_div,sign_macd_rsi_robust,sign_macd_rsi_simple,sign_macd_rsi_simple_break,sign_macd_rsi_simple_bb_pos,sign_macd_rsi_bb,sign_macd_rsi_bb_ema,ind_adx,sign_adx_crec,sign_adx_crec_rsi,sign_adx_rsi,sign_adx_rsi_robust,sign_adx_rsi_xtrem,sign_vpvma,sign_sinergia,sign_rsi_bb_rever,sign_ma_macd,str_squ_kel_bb,sign_gold,ind_3ema,sign_rsi30,sign_rsi20,sign_rsi15,trend_adx,sign_pullb_ema,sign_rsi_div,ind_vwap_deviation,sign_supo_resi,ind_volume_anomaly,ind_compress_range,sign_sobreextema,sign_stochastic,sign_cmf,sign_elderray,sign_willr,sign_donchian,sign_liquidsweep,sign_macd_div1,sign_macd_div3,sign_macd_div5,sign_random,sign_random2,sign_random3
Datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-09-12 08:00:00+00:00,115061.484375,115243.726562,114998.703125,115137.429688,1851052032,2025-09-12 08:00:00+00:00,114972.361655,114201.947778,112328.777592,54.645607,364.305485,415.721128,-51.415643,116001.970474,114975.407812,113948.845151,0.541925,18.236350,37.308467,393.313757,-9.702564e+09,-6.144626e+09,42.672089,28.354620,15.422744,114405.601562,111553.984375,-1.396384e+06,8.115243e+05,115431.417939,0.002130,705203404.8,705203404.8,True,sell,0.002887,-0.118751,116289.901719,-60.349080,116313.515625,113477.273438,0.007526,False,False,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,3.0,0,0,0,0,1,0,0,0,-1,0,0,0,0,0,0,0,0,0,0
2025-09-12 09:00:00+00:00,115003.023438,115127.859375,114886.812500,115068.054688,0,2025-09-12 09:00:00+00:00,114975.281825,114233.362510,112355.387003,53.604989,323.738842,397.324671,-73.585829,116008.677276,114991.544922,113974.412568,0.505643,6.272598,20.917318,382.437551,-9.702564e+09,-6.483478e+09,41.293581,27.078073,16.818202,114071.804688,111554.617188,-1.969429e+06,2.819317e+05,115431.417939,0.002096,705203404.8,705203404.8,False,sell,0.002554,-0.118751,116238.253775,-64.322828,116313.515625,113948.765625,0.006738,False,False,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,3.0,1,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,1,0,0
2025-09-12 10:00:00+00:00,114993.804688,115056.570312,114978.492188,115038.914062,0,2025-09-12 10:00:00+00:00,114977.045907,114263.183772,112381.639915,53.432194,287.531130,375.365963,-87.834833,116007.322478,115015.749219,114024.175959,0.488934,9.664673,11.391207,360.697592,-9.702564e+09,-6.790057e+09,40.013539,26.659399,16.558163,114067.031250,111832.523438,-3.007791e+06,-3.844666e+05,115431.417939,0.000679,655557017.6,655557017.6,False,sell,0.002526,-0.175974,116157.167299,-69.435630,116313.515625,114046.375000,0.006394,False,False,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,3.0,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,0,0,0,1,0
2025-09-12 11:00:00+00:00,114938.054688,115136.171875,114930.914062,114987.226562,0,2025-09-12 11:00:00+00:00,114973.332457,114289.649298,112407.076878,52.333536,251.439262,350.580623,-99.141360,115963.927236,115054.151953,114144.376670,0.436195,10.235664,8.724312,349.594751,-9.702564e+09,-7.067439e+09,39.031797,27.167764,15.863749,113860.000000,112519.710938,-3.246512e+06,-9.608089e+05,115431.417939,0.001786,655557017.6,655557017.6,False,sell,0.002421,-0.175974,116080.946011,-75.484374,116313.515625,114139.515625,0.005673,False,False,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2.0,0,0,0,0,0,0,0,1,-1,1,0,0,0,0,0,0,0,0,0
2025-09-12 12:00:00+00:00,115126.804688,115176.851562,114804.148438,114950.421875,0,2025-09-12 12:00:00+00:00,114987.948860,114322.478921,112434.138846,55.657857,235.353734,327.535245,-92.181511,115960.761009,115083.465234,114206.169460,0.524701,19.005358,12.968565,351.245349,-9.702564e+09,-7.318403e+09,37.571146,25.108660,17.239282,114066.000000,112388.742188,-2.706228e+06,-1.379011e+06,115431.417939,0.003237,591357952.0,591357952.0,False,buy,0.002345,-0.277921,116009.298000,-78.623078,116313.515625,114139.515625,0.007036,False,False,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2.0,1,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,-1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-10-05 23:00:00+00:00,85748.953125,86061.710938,85717.078125,85929.398438,0,2026-10-05 23:00:00+00:00,85795.511765,85607.857202,84741.386204,49.605254,15.392586,38.971769,-23.579183,86500.287529,85842.158594,85184.029658,0.429189,60.613110,53.667584,370.163578,-1.141744e+11,-1.146686e+11,16.718027,23.423622,20.626965,85851.992188,84836.992188,-1.243642e+06,8.986674e+05,85892.284266,0.004019,727466700.8,727466700.8,False,sell,0.003807,-0.003627,86281.164658,-55.423730,86713.906250,84972.859375,0.001648,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1.0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0
2026-10-06 00:00:00+00:00,85901.968750,85968.570312,85762.320312,85766.773438,0,2026-10-06 00:00:00+00:00,85805.650526,85619.390988,84752.934289,52.503293,23.240365,35.825488,-12.585124,86501.017214,85861.985156,85222.953098,0.531284,70.515370,61.094767,359.410264,-1.141744e+11,-1.146215e+11,15.977364,22.401267,19.726674,86423.906250,84739.203125,-1.569994e+06,2.384597e+05,NaN,0.002401,666728140.8,666728140.8,False,buy,0.003538,0.075584,86228.832447,-46.635017,86713.906250,84972.859375,0.003300,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1.0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2026-10-06 01:00:00+00:00,85613.328125,86131.468750,85594.757812,85950.453125,0,2026-10-06 01:00:00+00:00,85787.334107,85619.153229,84761.495421,47.011326,6.098599,29.880111,-23.781511,86502.237995,85855.641406,85209.044817,0.312624,66.960593,66.029691,372.074598,-1.141744e+11,-1.145789e+11,14.978573,20.093165,20.910908,86512.976562,84708.570312,-7.166729e+05,-2.057897e+05,NaN,0.006269,631664742.4,631664742.4,False,sell,0.003573,0.029009,86178.593524,-63.213584,86713.906250,84972.859375,-0.000068,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-0.0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2026-10-06 02:00:00+00:00,85525.109375,85745.640625,85448.281250,85656.531250,1283969024,2026-10-06 02:00:00+00:00,85762.360323,85615.465235,84769.093570,45.446626,-14.438452,21.016398,-35.454850,86457.833516,85820.391016,85182.948516,0.268386,50.886692,62.787552,366.737796,-1.154584e+11,-1.146627e+11,14.532570,18.929451,22.552720,86632.000000,84755.953125,-9.281366e+05,-5.378836e+05,85525.109375,0.003477,670759321.6,670759321.6,True,sell,0.003307,-0.043504,86131.468750,-68.280578,86713.906250,84972.859375,-0.001055,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,-1
2026-10-06 03:00:00+00:00,85520.570312,85580.742188,85499.250000,85529.429688,15284224,2026-10-06 03:00:00+00:00,85739.332703,85611.743865,84776.570951,45.362965,-30.726284,10.667862,-41.394146,86404.043865,85784.655469,85165.267073,0.286818,25.970641,47.939309,346.363110,-1.154737e+11,-1.147399e+11,14.118423,18.611328,22.173706,86605.101562,84742.218750,-1.749893e+06,-8.889434e+05,85525.055978,0.000953,602931916.8,602931916.8,False,sell,0.003306,-0.019864,86131.468750,-68.541287,86713.906250,84972.859375,-0.001065,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
cols_sign = [col for col in df.columns if col.startswith("sign_")] 
cols_indic = [col for col in df.columns if not col.startswith("sign_")] 
order = sorted(cols_sign)
df = df[order]

print("Signals   :", len(cols_sign))
print("Indicators:", len(cols_indic))

Signals   : 35
Indicators: 51

In [5]:
res = []
for j in cols_sign:
    buys = df[df[j].isin([1])].shape[0]
    sells = df[df[j] == -1].shape[0] 
    n = buys + sells
    res.append(pd.DataFrame({"signal":[j], "n":[n], "%":[(n/len(df))*100], "buys":[buys], "buys%":[(buys/len(df))*100],
                              "sells":[sells],"sells%":[(sells/len(df))*100]}))
print(len(df))
res = pd.concat(res).sort_values("%", ascending = False)
res.head(20)

9300

              signal     n          %  buys      buys%  sells     sells%
0           sign_cmf  4186  45.010753  1790  19.247312   2396  25.763441
0       sign_ma_macd  3681  39.580645  1760  18.924731   1921  20.655914
0      sign_adx_crec  2319  24.935484  1027  11.043011   1292  13.892473
0       sign_random3  1835  19.731183   926   9.956989    909   9.774194
0     sign_pullb_ema  1602  17.225806   772   8.301075    830   8.924731
0         sign_vpvma  1402  15.075269   672   7.225806    730   7.849462
0      sign_elderray  1299  13.967742   619   6.655914    680   7.311828
0         sign_willr  1283  13.795699   616   6.623656    667   7.172043
0         sign_rsi30  1039  11.172043   504   5.419355    535   5.752688
0     sign_macd_div5   983  10.569892   490   5.268817    493   5.301075
0      sign_donchian   952  10.236559   470   5.053763    482   5.182796
0        sign_random   939  10.096774   472   5.075269    467   5.021505
0   sign_liquidsweep   897   9.645161   432   4.645161    465   5.000000
0      sign_sinergia   772   8.301075   411   4.419355    361   3.881720
0    sign_stochastic   728   7.827957   341   3.666667    387   4.161290
0   sign_sobreextema   623   6.698925   401   4.311828    222   2.387097
0     sign_macd_div3   594   6.387097   297   3.193548    297   3.193548
0  sign_rsi_bb_rever   578   6.215054   293   3.150538    285   3.064516
0     sign_supo_resi   565   6.075269   277   2.978495    288   3.096774
0       sign_random2   474   5.096774   227   2.440860    247   2.655914